/* ============================================================================
   QUINTAESENCIA_BATS — Significados específicos de la Quintaesencia
   Estructura: objeto plano indexado por nombre de arcano mayor (nombre → texto).
   El número de quintaesencia (1-22, El Loco = 22) NO es un campo de este objeto;
   se resuelve en el módulo de cálculo y debe mapearse a estas claves por nombre.
   Cada texto sigue el esquema fijo: diagnóstico · CONSEJO · PALABRA CLAVE · ANTIPATRÓN.
   CONSEJO se dirige siempre al consultante (registro unificado, auditoría 2026-08).
   ============================================================================ */
var QUINTA_BATS = {
  "El Mago": "El proceso descrito está en su centro activo; no hay destino impersonal, la dirección pertenece a quien actúa.  CONSEJO: tomar la iniciativa y actuar con lo disponible, sin esperar a que el destino resuelva por sí solo. El Mago no promete éxito; promete capacidad.  PALABRA CLAVE: inicio activo.  ANTIPATRÓN: \"salió El Mago, así que es buen momento para empezar\" — niega los bloqueos que puedan mostrar las demás cartas.",
  "La Sacerdotisa": "Lo que se busca no se obtiene por acción sino por espera atenta; la información necesaria es interna, no externa.  CONSEJO: esperar y escuchar la información interna; no forzar una decisión en este momento.  PALABRA CLAVE: espera atenta.  ANTIPATRÓN: \"todo está oculto, no podemos avanzar\" — paraliza indebidamente si hay cartas activas que indican dirección concreta.",
  "La Emperatriz": "Proceso en fase de maduración fértil; los recursos están disponibles, lo que falta es gestación, no consecución.  CONSEJO: cultivar con paciencia.  PALABRA CLAVE: fecundidad paciente.  ANTIPATRÓN: \"todo será abundante\" — malinterpreta como promesa material sin siembra.",
  "El Emperador": "La estructura y el orden son el campo dominante; el proceso debe alinearse con un principio estructurante.  CONSEJO: estructurar; autoridad funcional, no imposición.  PALABRA CLAVE: orden funcional.  ANTIPATRÓN: \"debes imponerte\" — confunde autoridad funcional con coerción.",
  "El Hierofante": "El proceso está mediado por una instancia institucional o doctrinal externa con la que hay que alinearse o dialogar.  CONSEJO: buscar intermediario, consultar doctrina establecida.  PALABRA CLAVE: tradición mediadora.  ANTIPATRÓN: \"no cambies nada, sigue la tradición\" — riesgo de dogmatismo cuando las cartas muestran conflicto activo.",
  "Los Enamorados": "El proceso presenta una polaridad que exige integración, o bien una elección genuina entre dos opciones reales — según confirmen las demás cartas; lo que se decide o se une define identidad, no conveniencia.  CONSEJO: hacer consciente la opción o la unión, no postergar, aceptar la pérdida inherente a toda elección.  PALABRA CLAVE: elección identitaria.  ANTIPATRÓN: \"elige el amor\" — reduce una decisión identitaria a sentimentalismo; tampoco toda aparición de esta carta implica disyuntiva, puede señalar unión de opuestos en vez de elección entre ellos.",
  "El Carro": "Proceso en fase de avance con dirección clara y voluntad en acción; hay control, lo que falta es sostenimiento.  CONSEJO: mantener el rumbo, sostener el ritmo.  PALABRA CLAVE: avance disciplinado.  ANTIPATRÓN: \"todo está controlado\" — olvida que El Carro exige atención sostenida; el control actual no equivale a haber llegado.",
  "La Fuerza": "El proceso requiere templar la energía instintiva o impulsiva antes de cualquier otra operación; sin esa templanza no hay acción sostenible.  CONSEJO: templar el impulso sin suprimir la energía.  PALABRA CLAVE: templanza del impulso.  ANTIPATRÓN: \"debes controlar todo\" — confunde templar con reprimir.",
  "El Ermitaño": "El proceso requiere aislamiento reflexivo; la respuesta no está en el colectivo sino en el diálogo interno de quien consulta.  CONSEJO: retirarse, distinguir lo propio de lo ajeno.  PALABRA CLAVE: introspección iluminadora.  ANTIPATRÓN: \"estás solo\" — confunde aislamiento epistemológico con aislamiento social.",
  "La Rueda de la Fortuna": "El proceso está gobernado por fuerzas cíclicas impersonales más allá del control del consultante; la acción posible es leer el momento del ciclo y ajustarse.  CONSEJO: observar el giro, aceptar la fase, flexibilidad operativa.  PALABRA CLAVE: lectura del ciclo.  ANTIPATRÓN: \"es destino, nada que hacer\" — paraliza falsamente; lo impersonal no excluye la adaptación inteligente.",
  "La Justicia": "La situación es producto de decisiones anteriores identificables; lo que acontece es consecuencia reconocible, y la decisión actual debe sopesarse en balanza.  CONSEJO: evaluar consecuencias, medir antes de actuar, aceptar la responsabilidad de las decisiones.  PALABRA CLAVE: balanza decisional.  ANTIPATRÓN: \"es un karma, acepta\" — determinismo indebido: La Justicia equilibra, no elimina la libertad de la decisión presente.",
  "El Colgado": "Proceso detenido intencionalmente o en pausa activa; la quietud es operativa, no inerte.  CONSEJO: soltar el control directivo, ver la situación desde otro ángulo, aceptar la pausa.  PALABRA CLAVE: suspensión lúcida.  ANTIPATRÓN: \"todo está paralizado\" — invisibiliza la agencia posible dentro de la pausa.",
  "La Muerte": "Se exige transformación radical: lo viejo debe morir simbólicamente para que algo nuevo ocupe su lugar. No es tragedia, es rotación: la lectura cualitativa es \"ciclos que se cierran\", nunca muerte física.  CONSEJO: aceptar el final de la forma, no alentar permanencia forzosa.  PALABRA CLAVE: transformación necesaria.  ANTIPATRÓN: \"alguien va a morir\" — violación ética directa; la carta es simbólica.",
  "La Templanza": "Dos elementos deben integrarse en proporción; la operación de mezcla armónica es central.  CONSEJO: medir proporciones, integrar sin forzar, paciencia.  PALABRA CLAVE: mezcla armónica.  ANTIPATRÓN: \"está todo equilibrado\" — ignora posible desequilibrio activo en las demás cartas.",
  "El Diablo": "El sistema descrito está atrapado en una atadura que se percibe como costosa de romper; se expone como observable, sin dramatizarla.  CONSEJO: identificar la cadena, distinguir apego de elección, no estigmatizar la atadura como mal absoluto.  PALABRA CLAVE: atadura observable.  ANTIPATRÓN: \"todo está mal\" — confunde sombra con mal.",
  "La Torre": "La estructura previa está en proceso de colapso o acaba de colapsar; la caída es violenta pero libera lo verdadero.  CONSEJO: dejar caer, no reconstruir sobre cimientos falsos.  PALABRA CLAVE: ruptura liberadora.  ANTIPATRÓN: \"todo se viene abajo\" — confunde un diagnóstico de estado con predicción de evento.",
  "La Estrella": "Proceso post-crisis donde emerge claridad serena; la reconstrucción es posible porque la visión ha sido restaurada.  CONSEJO: confiar en la guía interna, reconstruir con esperanza calibrada.  PALABRA CLAVE: esperanza operativa.  ANTIPATRÓN: \"está salvado\" — sobre-promete; La Estrella es relativa a la crisis previa, no absoluta.",
  "La Luna": "El proceso atraviesa territorio inconsciente donde percepción y realidad se confunden; la cautela perceptual es indispensable.  CONSEJO: desconfiar de la primera lectura, distinguir miedo de peligro.  PALABRA CLAVE: navegación por el inconsciente.  ANTIPATRÓN: \"nada es real, todo es engaño\" — patologiza el inconsciente en vez de integrarlo.",
  "El Sol": "Proceso en fase de visibilidad y consolidación plena; lo que se gesta emerge con nitidez.  CONSEJO: dejar emerger, celebrar sin exagerar.  PALABRA CLAVE: plenitud visible.  ANTIPATRÓN: \"todo es éxito garantizado\" — sobre-promete; El Sol no garantiza sostenibilidad, solo plenitud en la fase presente.",
  "El Juicio": "Momento de evaluación global; el proceso se somete a un llamado de conciencia donde nada relevante queda oculto, y la transformación se inicia por aceptación.  CONSEJO: rendir cuentas, aceptar el llamado, dejar emerger lo verdadero.  PALABRA CLAVE: evaluación definitiva.  ANTIPATRÓN: \"vas a ser juzgado\" — confunde metáfora con tribunal real; puede activar ansiedad indebida.",
  "El Mundo": "Proceso que ha llegado a integración plena del ciclo descrito por las cartas; lo consultado se cierra como ciclo completo en el nivel simbólico.  CONSEJO: reconocer el cierre del ciclo, integrar aprendizajes, preparar la semilla del siguiente ciclo.  PALABRA CLAVE: cierre integrado.  ANTIPATRÓN: \"todo se acabó\" — malinterpreta fin de ciclo con fin del proceso.",
  "El Loco": "Como terminal: la tirada cierra como llamada al inicio radical, volver a cero sin coordenadas previas. Como presencia en la tirada: introduce incertidumbre sobre cualquier cierre numérico derivado de la suma, aumentando el peso simbólico de \"margen fuera del sistema\".  CONSEJO: soltar estructuras previas, aceptar el inicio en cero, no aferrarse a interpretaciones fijas.  PALABRA CLAVE: reinicio sin coordenadas.  ANTIPATRÓN: \"salió El Loco, la tirada no cierra / todo es caos\" — confunde ausencia de coordenadas con ausencia de diagnóstico; el margen fuera del sistema es un dato leíble, no una anulación de la lectura."
};
